services:
  postgres:
    image: postgres:15
    container_name: consumer-loyalty-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: consumer_loyalty_admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: consumer_loyalty_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - consumer-loyalty-network

networks:
  consumer-loyalty-network:
    driver: bridge

volumes:
  postgres_data: